{{- $fullname := include "clinicdesk.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-backend
  labels:
    {{- include "clinicdesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxUnavailable: 0, maxSurge: 1}
  selector:
    matchLabels:
      {{- include "clinicdesk.selectorLabels" (dict "ctx" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clinicdesk.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- include "clinicdesk.podSecurity" (dict "ctx" . "uid" 10001) | nindent 6 }}
      containers:
        - name: backend
          image: {{ include "clinicdesk.image" (dict "ctx" . "image" .Values.backend.image) | quote }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ $fullname }}-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef: {name: {{ include "clinicdesk.dbSecretName" . }}, key: username}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: {name: {{ include "clinicdesk.dbSecretName" . }}, key: password}
          startupProbe:
            httpGet: {path: /health, port: http}
            periodSeconds: 3
            failureThreshold: 40
          livenessProbe:
            httpGet: {path: /health, port: http}
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet: {path: /ready, port: http}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- include "clinicdesk.containerSecurity" (dict "readOnly" true) | nindent 10 }}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
      volumes:
        - {name: tmp, emptyDir: {}}
