apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinicdesk.fullname" . }}-frontend
  labels:
    {{- include "clinicdesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "clinicdesk.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
