{{- $fullname := include "clinicdesk.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-frontend
  labels:
    {{- include "clinicdesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxUnavailable: 0, maxSurge: 1}
  selector:
    matchLabels:
      {{- include "clinicdesk.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clinicdesk.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- include "clinicdesk.podSecurity" (dict "ctx" . "uid" 101) | nindent 6 }}
      containers:
        - name: frontend
          image: {{ include "clinicdesk.image" (dict "ctx" . "image" .Values.frontend.image) | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_UPSTREAM
              valueFrom:
                configMapKeyRef: {name: {{ $fullname }}-config, key: BACKEND_UPSTREAM}
          readinessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- include "clinicdesk.containerSecurity" (dict "readOnly" true) | nindent 10 }}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
            - {name: conf, mountPath: /etc/nginx/conf.d}
      volumes:
        - {name: tmp, emptyDir: {}}
        - {name: conf, emptyDir: {}}
